discovery:
  image: darrinsolomon/discovery-microservice
  ports:
   - "8761:8761"
configserver:
  image: darrinsolomon/config-microservice
  ports:
   - "8888:8888"
  links:
   - discovery
hello:
  image: darrinsolomon/hello
  links:
   - discovery
   - configserver
users:
  image: darrinsolomon/users
  ports:
     - "8085:8080"
  links:
   - discovery
   - configserver
orderdetails:
  image: darrinsolomon/orderdetails
  ports:
     - "8086:8080"
  links:
   - discovery
   - configserver
ssg:
  image: caapim/gateway
  mem_limit: 2048m
  expose:
    - "8777"
  ports:
    - "8080:8080"
    - "8443:8443"
  environment:
    SSG_CLUSTER_COMMAND: "create"
    SSG_CLUSTER_HOST: "localhost"
    SSG_CLUSTER_PASSWORD: "7layer"
    SSG_DATABASE_TYPE: "mysql"
    SSG_DATABASE_HOST: "mysql"
    SSG_DATABASE_PORT: "3306"
    SSG_DATABASE_NAME: "ssg"
    SSG_DATABASE_USER: "gateway"
    SSG_DATABASE_PASSWORD: "7layer"
    SSG_DATABASE_ADMIN_USER: "root"
    SSG_DATABASE_ADMIN_PASS: "7layer"
    SSG_ADMIN_USER: "pmadmin"
    SSG_ADMIN_PASS: "7layer"
    SSG_LICENSE:
    SSG_INTERNAL_SERVICES: "restman wsman"
  links:
    - mysql
    - configserver
    - hello
    - discovery
    - users
    - orderdetails
mysql:
  image: mysql:5.5
  mem_limit: 512m
#  volumes:
#    - ./mysqlconf:/etc/mysql/conf.d
#    - /root/mysqldatadir:/var/lib/mysql
  environment:
    - MYSQL_ROOT_PASSWORD=7layer