server:
  port: 8761

eureka:
  server:
    enableSelfPreservation: false
    response-cache-update-interval-ms: 500
    eviction-interval-timer-in-ms: 500
  instance:
    hostname: discovery
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://discovery:${server.port}/eureka/

spring.cloud.config.discovery.enabled: true
